//
//  Ride.swift
//  HSD
//
//  Created by rightmeow on 12/12/17.
//  Copyright © 2017 rightmeow. All rights reserved.
//

import Foundation
import RealmSwift

class Ride: Object {

    @objc dynamic var ride_id = ""
    @objc dynamic var driver_name = ""
    @objc dynamic var created_at: NSDate!
    @objc dynamic var updated_at: NSDate?
    @objc dynamic var pickup_date: NSDate?

    override static func primaryKey() -> String? {
        return "ride_id"
    }

    convenience init(ride_id: String, driver_name: String, pickup_date: NSDate) {
        self.init()
        self.ride_id = UUID().uuidString // in real life, this property is generated by the backend API
        self.driver_name = driver_name
        self.pickup_date = pickup_date
        self.created_at = NSDate()
        self.updated_at = nil
    }

}
